### ISSUE TITLE
daemon: Debug flag should have stager goes to to kurmad stdout

### ISSUE THREAD

**Issue by krobertson** [apcera/kurma#100]
When the debug flag is enable in Kurma's configuration, the podmanger should have the stager's logs (stdout/stderr) go to the daemon's own stdout/stderr instead of being sent to a log file.

This would allow the logs to be more immediately visible and be useful for troubleshooting as well as in the integration test runs, debugging failures.

**Comment by wallyqs** [comment]
Fixed via #106
