### ISSUE TITLE
Could you provider a guide for  container Beginners  about how to use Kurma?

### ISSUE THREAD

**Issue by wangkirin** [apcera/kurma#14]
Hello , I am a container beginer, could you provide a guide about how to install Kurma enviroment ,how to build a kurma image and how to use Kurma? thank you

**Comment by krobertson** [comment]
Yes, currently documentation is lacking on the project and this will be getting addressed. Currently I'm on paternity leave and haven't been actively managing the project or prioritizing items with the team, but will be having it done soon.

**Comment by krobertson** [comment]
Website has now launched with a documentation section. http://kurma.io/documentation
